name: Laravel

on:

  push:
    branches:
      - main
      - develop

  pull_request:
    branches:
      - main
      - develop

#  schedule:
#    - cron: '0 0 * * *'

jobs:
  laravel-analyse:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        php: [8.4]

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache composer dependencies
        uses: actions/cache@v4
        with:
          path: ~/.composer/cache/files
          key: composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            composer-

      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: json, dom, curl, libxml, mbstring, zip
          tools: composer:v2
          coverage: xdebug

      - name: Setup Problem Matches
        run: |
          echo "::add-matcher::${{ runner.tool_cache }}/php.json"
          echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"

      - name: Install PHP Dependencies
        run: composer install --optimize-autoloader --no-interaction --no-progress  --prefer-dist

      - name: Prepare Laravel Setup
        run: |
          cp .env.ci .env
          php artisan key:generate

      - name: Laravel Directory Permissions
        run: chmod -R 777 ./storage ./bootstrap/cache

      - name: Run Rector
        run: |
          composer rector

      - name: Run Pint
        run: |
          composer pint

      - name: Run PHPStan
        run: |
          composer phpstan

      - name: Run tests
        run: |
          composer phpunit
        env:
          DB_DATABASE: cicd_testing

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_DATABASE: cicd_testing
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=5s --health-timeout=5s --health-retries=3
